{
 "title": "Factory Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Machine Vibration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "vibration" }
     ],
     "queryText": "SELECT vibration, time, \"machineID\" FROM iox.machine_data WHERE $__timeRange(time) ORDER BY time",
     "table": "machine_data",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Machine 1 - Load",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT  selector_last(load, time)['value'] AS load FROM iox.machine_data WHERE\"machineID\" = 'machine1' AND $__timeRange(time) "
    }
   ]
  },
  {
   "title": "Machine 2 - Load",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT   selector_last(load, time)['value'] AS load FROM iox.machine_data WHERE\"machineID\" = 'machine2' AND $__timeRange(time) "
    }
   ]
  },
  {
   "title": "Machine Health Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT\n    \"machineID\",\n    time,\n    CASE \n        WHEN (\n            CASE \n                WHEN temperature BETWEEN 35 AND 40 THEN 1\n                ELSE 0\n            END +\n            CASE \n                WHEN vibration BETWEEN 80 AND 90 THEN 2\n                ELSE 0\n            END +\n            CASE \n                WHEN power BETWEEN 200 AND 220 THEN 1\n                ELSE 0\n            END\n        ) < 2 THEN false\n        ELSE true\n    END AS \"Health:\"\nFROM\n    \"machine_data\"\nWHERE $__timeRange(time) \nORDER BY\n    \"machineID\",\n    time;"
    }
   ]
  },
  {
   "title": "Machine 3 - Load",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT  selector_last(load, time)['value'] AS load FROM iox.machine_data WHERE\"machineID\" = 'machine3' AND $__timeRange(time) "
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT selector_last(temperature, time)['value'] as \"Temperature:\", \"machineID\" FROM iox.machine_data WHERE $__timeRange(time) GROUP BY  \"machineID\" ORDER BY \"machineID\""
    }
   ]
  },
  {
   "title": "Machine Health Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n    \"machineID\",\n    time,\n    (\n        CASE \n            WHEN temperature BETWEEN 35 AND 40 THEN 1\n            ELSE 0\n        END +\n        CASE \n            WHEN vibration BETWEEN 80 AND 90 THEN 2\n            ELSE 0\n        END +\n        CASE \n            WHEN power BETWEEN 200 AND 220 THEN 1\n            ELSE 0\n        END\n    ) AS health_score\nFROM\n    \"machine_data\"\nWHERE $__timeRange(time) \nORDER BY\n    \"machineID\",\n    time"
    }
   ]
  }
 ]
}