{
 "title": "Machine Data",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Machine 1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "vibration" }
     ],
     "queryText": "SELECT vibration, time, \"machineID\" FROM iox.machine_data WHERE \"machineID\"= 'machine1' AND $__timeRange(time)",
     "table": "machine_data",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Machine 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "vibration" }
     ],
     "queryText": "SELECT vibration, time, \"machineID\" FROM iox.machine_data WHERE \"machineID\"= 'machine2' AND $__timeRange(time)",
     "table": "machine_data",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Machine 3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "columns": [
      { "value": "vibration" }
     ],
     "queryText": "SELECT vibration, time, \"machineID\" FROM iox.machine_data WHERE \"machineID\"= 'machine3' AND $__timeRange(time)",
     "table": "machine_data",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Machine 1 - Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "columns": [
      { "value": "vibration" }
     ],
     "queryText": "SELECT time, \"machineID\", anomalies FROM iox.machine_data_aggregated WHERE \"machineID\"= 'machine1' AND $__timeRange(time)",
     "table": "machine_data",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Machine 2 - Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "columns": [
      { "value": "vibration" }
     ],
     "queryText": "SELECT time, \"machineID\", anomalies FROM iox.machine_data_aggregated WHERE \"machineID\"= 'machine2' AND $__timeRange(time)",
     "table": "machine_data",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Machine 3 - Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "columns": [
      { "value": "vibration" }
     ],
     "queryText": "SELECT time, \"machineID\", anomalies FROM iox.machine_data_aggregated WHERE \"machineID\"= 'machine3' AND $__timeRange(time)",
     "table": "machine_data",
     "wheres": [
      { "value": "" }
     ]
    }
   ]
  }
 ]
}