{
 "title": "Machine Check",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "MachineID ",
    "query": "SHOW TAG VALUES WITH KEY = \"machineID\""
   }
  ]
 },
 "panels": [
  {
   "title": "Machine Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT * FROM \"machine_data\" WHERE $timeFilter AND \"machineID\" = '$machine' ORDER BY ASC LIMIT 1"
    }
   ]
  },
  {
   "title": "Raw Vibration (Mean)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "SELECT mean(\"vibration\"), max(\"vibration\"), min(\"vibration\") FROM \"machine_data\" WHERE $timeFilter AND \"machineID\" = '$machine' GROUP BY time($__interval)  fill(previous)"
    }
   ]
  },
  {
   "title": "Vibration (log10)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 13, "y": 4 },
   "targets": [
    {
     "query": "SELECT LOG(\"vibration\", 10) FROM \"machine_data\" WHERE $timeFilter AND \"machineID\" = '$machine' "
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"load\") FROM \"machine_data\" WHERE \"machineID\" = '$machine' AND $timeFilter "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT temperature FROM \"machine_data\" WHERE $timeFilter AND \"machineID\" = '$machine' "
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "query": "SELECT power FROM \"machine_data\" WHERE $timeFilter AND \"machineID\" = '$machine' "
    }
   ]
  }
 ]
}