FROM python:3

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN rm requirements.txt

# Copy app
COPY  ./src/main.py ./main.py


CMD [ "python", "./main.py"]